---

- hosts: all
  remote_user: root
  become: yes

  tasks:
  - name: ensure python-apt and unzip are installed
    apt: name='python-apt,unzip'

#  - name: add php repository
#    apt_repository:
#      repo: 'ppa:ondrej/php'
#      update_cache: true

  - name: ensure php 7.4 is installed
    apt: name='php,php-zip,php-xml,php-mbstring,php-intl,php-mongodb'

  - name: ensure getcomposer is executable
    file: 
      path: /vagrant/files/getcomposer.sh
      mode: "+x"

  - name: get composer
    command: /vagrant/files/getcomposer.sh
    args:
      creates: /usr/local/bin/composer

  - name: stop apache2
    service:
      name: apache2
      state: stopped

  - name: create project directory
    file:
      src: /vagrant/src
      dest: /var/ranking
      state: link

  - name: add mongo repository key
    apt_key:
       keyserver: https://www.mongodb.org/static/pgp/server-5.0.asc
       id: B00A0BD1E2C63C11

  - name: create a list file for mongodb
    shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
    args:
      creates: /etc/apt/sources.list.d/mongodb-org-5.0.list

  - name: install mongo
    apt: 
      name: mongodb-org
      update_cache: true

  - name: start mongo
    service:
      name: mongod
      state: started

  - name: Download nodejs install script
    get_url:
      url: https://deb.nodesource.com/setup_14.x
      dest: /tmp/install_node.sh
      mode: 777

  - name: run nodejs install script
    command: /tmp/install_node.sh
    args:
      creates: /etc/apt/sources.list.d/nodesource.list

  - name: install nodejs
    apt:
      name: nodejs
      update_cache: true
  
#  - name: add yarn repository key
#    apt_key:
#      url: https://dl.yarnpkg.com/debian/pubkey.gpg
#      state: present
#
#  - name: add yarn source list
#    shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#    args:
#      creates: /etc/apt/sources.list.d/yarn.list
#
#  - name: install yarn
#    apt:
#      name: yarn
#      install_recommends: false
#      update_cache: true

#  - name: ensure php 7.4 is the default
#    shell: update-alternatives --set php /usr/bin/php7.4

