---

- hosts: all
  remote_user: root
  become: yes

  tasks:
  - name: ensure python-apt and unzip are installed
    apt: name='python-apt,unzip'

  - name: add php repository
    apt_repository:
      repo: 'ppa:ondrej/php'
      update_cache: true

  - name: ensure php 8.1 is installed
    apt: name='php8.1,php8.1-zip,php8.1-xml,php8.1-mbstring,php8.1-intl,php8.1-mongodb,php8.1-curl'

  - name: ensure getcomposer is executable
    file: 
      path: /vagrant/files/getcomposer.sh
      mode: "+x"

  - name: get composer
    command: /vagrant/files/getcomposer.sh
    args:
      creates: /usr/local/bin/composer

  - name: ensure security checker is executable
    file:
      path: /vagrant/files/local-php-security-checker
      mode: "+x"

  - name: link security checker to bin dir
    file:
      src: /vagrant/files/local-php-security-checker
      dest: /usr/local/bin/local-php-security-checker
      state: link

  - name: stop apache2
    service:
      name: apache2
      state: stopped

  - name: create project directory
    file:
      src: /vagrant/src
      dest: /var/ranking
      state: link

  - name: add mongo repository key
    apt_key:
       keyserver: https://www.mongodb.org/static/pgp/server-5.0.asc
       id: B00A0BD1E2C63C11

  - name: create a list file for mongodb
    shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
    args:
      creates: /etc/apt/sources.list.d/mongodb-org-5.0.list

  - name: install mongo
    apt: 
      name: mongodb-org
      update_cache: true

  - name: start mongo
    service:
      name: mongod
      state: started

  - name: create a list file for symfony-cli
    shell:  echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | sudo tee /etc/apt/sources.list.d/symfony-cli.list
    args:
      creates: /etc/apt/sources.list.d/symfony-cli.list

  - name: install symfony-cli
    apt:
      name: symfony-cli
      update_cache: true

  - name: Download nodejs install script
    get_url:
      url: https://deb.nodesource.com/setup_14.x
      dest: /tmp/install_node.sh
      mode: 777

  - name: run nodejs install script
    command: /tmp/install_node.sh
    args:
      creates: /etc/apt/sources.list.d/nodesource.list

  - name: install nodejs
    apt:
      name: nodejs
      update_cache: true

  - name: ensure npm is up to date
    shell: npm install -g npm


  - name: ensure php 8.1 is the default
    shell: update-alternatives --set php /usr/bin/php8.1

