tournament_list:
    path:     /api/tournaments
    controller: App\Controller\TournamentController::listTournaments
    methods:
      - GET

tournament_data:
    path:     /api/tournaments/{id}
    controller: App\Controller\TournamentController::getTournament
    methods:
      - GET

add_tournament:
    path:     /api/tournaments
    controller: App\Controller\TournamentController::addTournament
    methods:
      - POST

players_list:
    path: /api/players
    controller: App\Controller\PlayerController::listPlayers
    methods:
      - GET

create_player:
    path: /api/players
    controller: App\Controller\PlayerController::createPlayer
    methods:
      - POST

tournament_results:
    path: /api/tournament-results
    controller: App\Controller\ResultsController::createTournamentResults
    methods:
      - POST

ranking:
    path: /api/ranking
    controller: App\Controller\RankingController::list
    methods:
      - GET

recalculate_ranking:
    path: /api/ranking-commands/recalculate
    controller: App\Controller\SeasonController::recalculateRanking
    methods:
      - PUT

individual_ranking:
    path: /api/ranking/{seasonId}/{playerId}
    controller: App\Controller\RankingController::individual
    methods:
      - GET

frontend:
    path: /{token}
    controller: App\Controller\FrontController::front
    methods:
      - GET
    requirements:
      token: ".*"