services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    App\DataFixtures\:
        resource: '%kernel.project_dir%/src/DataFixtures'
        exclude: '%kernel.project_dir%/src/DataFixtures/MongoDB/{Development,FixturesBase.php}'
        tags: ['doctrine.fixture.orm']
