on:
  workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'https://ranking.wfb-pol.org'

